# --- app.yaml (Actualizado para usar SendGrid de forma segura) ---
runtime: python311
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  # La URL de la base de datos sigue igual
  DATABASE_URL: >-
    postgresql+psycopg2://postgres:XS-O?nv)en#qsj-6@/postgres?host=/cloudsql/proyecto-de-plataformas-465221:southamerica-west1:db-proyecto-plataformas
  
  # La clave de API de SendGrid ha sido removida.
  # Ahora se cargará de forma segura desde Google Secret Manager.

beta_settings:
  cloud_sql_instances: proyecto-de-plataformas-465221:southamerica-west1:db-proyecto-plataformas
