runtime: python311
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  DATABASE_URL: >-
    postgresql+psycopg2://postgres:plataformasH1@/postgres?host=/cloudsql/proyecto-de-plataformas-465221:southamerica-west1:db-proyecto-plataformas

beta_settings:
  cloud_sql_instances: proyecto-de-plataformas-465221:southamerica-west1:db-proyecto-plataformas
