# --- app.yaml (Versión Segura y Final) ---
runtime: python311
entrypoint: gunicorn -b :$PORT app:app

# Variables de entorno que pasaremos a nuestra aplicación
env_variables:
  # La URL de la base de datos
  DATABASE_URL: >-
    postgresql+psycopg2://postgres:XS-O?nv)en#qsj-6@/postgres?host=/cloudsql/proyecto-de-plataformas-465221:southamerica-west1:db-proyecto-plataformas
  
 # --- CLAVE DE API DE SENDGRID ---
  # Para esta prueba, pon aquí tu clave de API de SendGrid válida y nueva.
  SENDGRID_API_KEY: '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'

beta_settings:
  cloud_sql_instances: proyecto-de-plataformas-465221:southamerica-west1:db-proyecto-plataformas



