# --- app.yaml (Versi칩n Segura y Final) ---
runtime: python311
entrypoint: gunicorn -b :$PORT app:app

# Variables de entorno que pasaremos a nuestra aplicaci칩n
env_variables:
  # La URL de la base de datos
  DATABASE_URL: >-
    postgresql+psycopg2://postgres:XS-O?nv)en#qsj-6@/postgres?host=/cloudsql/proyecto-de-plataformas-465221:southamerica-west1:db-proyecto-plataformas
  
  # La clave de API de SendGrid ha sido removida de este archivo.
  # Ahora se cargar치 de forma segura desde Google Secret Manager,
  # como est치 configurado en el archivo app.py.

beta_settings:
  cloud_sql_instances: proyecto-de-plataformas-465221:southamerica-west1:db-proyecto-plataformas



