# Versión del runtime de Python que usará App Engine
runtime: python311

# Comando para iniciar la aplicación web
entrypoint: gunicorn -b :$PORT app:app

# Variables de entorno que pasaremos a nuestra aplicación
env_variables:
  # Esta es la URL de conexión completa para nuestra base de datos
  # SQLAlchemy la usará para conectarse.
  DATABASE_URL: >-
    postgresql+psycopg2://postgres:plataformasH1@/postgres?host=/cloudsql/proyecto-de-plataformas-465221:southamerica-west1:db-proyecto-plataformas

# Configuración para la conexión con Cloud SQL
beta_settings:
  cloud_sql_instances: proyecto-de-plataformas-465221:southamerica-west1:db-proyecto-plataformas
